[workspace]
resolver = "2"
members = [
    "werbolg-core",
    "werbolg-compile",
    "werbolg-exec",
    "werbolg-lang-common",
    "werbolg-lang-rusty",
    "werbolg-lang-lispy",
    "werbolg-ir-write",
    "werbolg-tests",
    "werbolg-example1",
]
